[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
proc-macro2 = "1.0.86"
quote = "1.0.37"
ungrammar = "1.16.1"
itertools.workspace = true
xshell.workspace = true
clap = { workspace = true, features = ["derive"] }
